apiVersion: v1
kind: Service
metadata:
  name: metasfresh-{{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: metasfresh-{{ .Release.Name }}-db
spec:
  selector:
    app: metasfresh-{{ .Release.Name }}-db
  ports:
  - name: db
    port: {{ .Values.db.port.db }}
    protocol: TCP
    targetPort: {{ .Values.db.port.db }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metasfresh-{{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: metasfresh-{{ .Release.Name }}-db
spec:
  selector:
    matchLabels:
        app: metasfresh-{{ .Release.Name }}-db
  serviceName: metasfresh-{{ .Release.Name }}-db
  replicas: 1
  template:
    metadata:
      labels:
        app: metasfresh-{{ .Release.Name }}-db
    spec:
      containers:
      - name: metasfresh-{{ .Release.Name }}-db
        image: {{ .Values.db.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.db.port.db }}
        env:
        - name: PGDATA
          value: /db/data
        args: ["-cconfig_file=/etc/postgresql/postgresql.conf"]
        volumeMounts:
        - name: postgresql-config
          mountPath: /etc/postgresql
        - name: data
          mountPath: db         
        - name: host-localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: host-timezone
          mountPath: /etc/timezone
          readOnly: true
      initContainers:      
        - name: init-postgres
          image: {{ .Values.db.imageInit }}
          imagePullPolicy: IfNotPresent
          env:
          - name: DB_NAME
            value: {{ .Values.db.name }}
          - name: DB_PORT
            value: '{{ .Values.db.port.db }}'
          - name: PGDATA
            value: /db/data
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: metasfresh-{{ .Release.Name }}-db-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: metasfresh-{{ .Release.Name }}-db-secret
                key: password
          - name: DEBUG_PRINT_BASH_CMDS
            value: {{ .Values.db.debug.printBashCmds }}
          - name: URL_SEED_DUMP
            value: {{ .Values.db.urlSeedDump }}
          - name: URL_MIGRATION_SCRIPTS_PACKAGE
            value: {{ .Values.db.urlMigrationScript }}
          volumeMounts:
          - name: host-localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: host-timezone
            mountPath: /etc/timezone
            readOnly: true
          - name: data
            mountPath: db
      volumes:
      - name: postgresql-config
        configMap:
          name: metasfresh-{{ .Release.Namespace }}-db-configmap
      - name: host-localtime
        hostPath:
          path: /etc/localtime
      - name: host-timezone
        hostPath:
          path: /etc/timezone
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: {{ .Release.Namespace }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage

