apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  {{ if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.webui.url }}
    {{ if .Values.ingress.pgadmin.enabled }}
    - {{ .Values.ingress.pgadmin.url }}
    {{ end }}
    secretName: {{ .Release.Name }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.ingress.webui.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metasfresh-{{ .Release.Name }}-webui
            port:
              number: {{ .Values.webui.port.webui }}
  {{ if .Values.ingress.pgadmin.enabled }}
  - host: {{ .Values.ingress.pgadmin.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metasfresh-{{ .Release.Name }}-pgadmin
            port:
              number: {{ .Values.pgadmin.port.pgadmin }}
  {{ end }}

  
