queue_rules:
  - name: default
    conditions:
      - check-success=testspace-analytics
      - check-success=continuous-integration/jenkins/branch

pull_request_rules:
  - name: When a project-PR is integrated, create a PR towards the master-branch
    conditions:
      - merged-at > '2023-03-15 00:00Z' # don't jump on every merged PR throughout history
      - or: &PROJECTBRANCHES # look 'ma, i'm doing https://docs.mergify.com/configuration/#yaml-anchors-and-aliases !
        # Please keep in sync with the branches at .testspace.yml
        - base=adorable_badger_uat
        - base=ant_pharm_uat
        - base=anxious_hippos_uat
        - base=arctic_north_uat
        - base=big_coconut_uat
        - base=blonde_monkey_uat
        - base=clone_wars_uat
        - base=hard_encoded_uat 
        - base=holy_cow_uat
        - base=hostile_tractor_uat
        - base=inner_silence_uat
        - base=intensive_care_uat
        - base=iron_plant_uat
        - base=epic_party_uat
        - base=mad_orange_uat
        - base=magic_oak_uat
        - base=neon_underwear_uat
        - base=nerdy_frog_uat 
        - base=pot_hole_uat 
        - base=release
        - base=scary_plum_uat
        - base=science_vessel_uat
        - base=secondary_opinion_uat
        - base=tasty_ham_uat
        - base=tenacious_d_uat
        - base=week_end_uat
        - base=yoyo_uat
    actions:
      copy:
        branches:
          - master
        assignees: # the original PR's author shall be notified when the merge-towards-master build fails
          - "{{ author }}"
        labels:  
          - "ops:merge_towards_master"

  - name: When a project- or master-PR is integrated, add a label with the name of the branch
    conditions:
      - merged-at > '2023-03-15 00:00Z' # don't jump on every merged PR throughout history
      - or: &BASEBRANCHES # this rule should apply to both the project-branches from above, and master
        - or: *PROJECTBRANCHES
        - or:
          - base=master
    actions:
      label:
        add:
          - "branch:{{base}}"

  - name: Automatic squash-merge successful PRs into the base-branch
    conditions:
      - check-success=testspace-analytics
      - check-success=continuous-integration/jenkins/branch
      - or: *BASEBRANCHES
      - or:
        - "#approved-reviews-by>=1"
        - label=ops:without_review_approval
    actions:
      queue:
        name: default
        method: squash

  - name: Automatic merge PRs labeled with `ops:merge_towards_master` into the `master`-branch
    conditions:
      - check-success=testspace-analytics
      - check-success=continuous-integration/jenkins/branch
      - base=master
      - label=ops:merge_towards_master
    actions:
      queue:
        name: default
        method: merge
