# docker-compose.yml file

services:

  db:
    image: mazorn/metas-db:$mfversion-preloaded
    ports:
      - "15432:5432"
    healthcheck:
      test: pg_isready -h localhost -U metasfresh -d metasfresh -t 1
      interval: 5s
      timeout: 2s
      start_period: 10s
      retries: 120
    deploy:
      mode: replicated
      replicas: 1
      
  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=metasfresh
      - RABBITMQ_DEFAULT_PASS=metasfresh
      - RABBITMQ_DEFAULT_VHOST=/
    deploy:
      mode: replicated
      replicas: 1

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
      - "ES_JAVA_OPTS=-Xms128M -Xmx256m"
    deploy:
      mode: replicated
      replicas: 1

  webapi:
    image: mazorn/metas-api:$mfversion
    ports:
      - "8080:8080"
      - "8789:8789"
    environment:
      - "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS=search:9200"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1

  app:
    image: mazorn/metas-app:$mfversion
    ports:
      - "8282:8282"
      - "61616:61616"
      - "8788:8788"
    environment:
      - "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS=search:9200"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1

  external:
    image: mazorn/metas-externalsystems:$mfversion
    environment:
      - METASFRESH_API_BASEURL=http://app:8282/api
      - METASFRESH_API_V2_BASEURL=http://app:8282/api/v2
      - METASFRESH_ERROR-REPORT_FOLDER=file://app:8282/data/error
      - METASFRESH_API_AUTHTOKEN=37b5d80deb7a4ee098bdc82ff0971c84
      - CAMEL_COMPONENT_RABBITMQ_HOSTNAME=rabbitmq
      - CAMEL_COMPONENT_RABBITMQ_PORT=5672
      - CAMEL_COMPONENT_RABBITMQ_USERNAME=metasfresh
      - CAMEL_COMPONENT_RABBITMQ_PASSWORD=metasfresh
    depends_on:
      - app
    deploy:
      mode: replicated
      replicas: 1

  webui:
    image: mazorn/metas-frontend:$mfversion
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-config.js:/usr/share/nginx/html/config.js:ro
    depends_on:
      - webapi
      - app
    deploy:
      mode: replicated
      replicas: 1

  mobile:
    image: mazorn/metas-mobile:$mfversion
    ports:
      - "8880:80"
    volumes:
      - ./mobile-config.js:/usr/share/nginx/html/config.js:ro
    depends_on:
      - webapi
      - app
    deploy:
      mode: replicated
      replicas: 1

volumes: {}
configs: {}
secrets: {}
