name: cicd
on: [push]
jobs:

  init:
    runs-on: ubuntu-latest
    outputs:
      tag-floating: ${{ steps.sanitize.outputs.refname }}
      tag-fixed: ${{ steps.sanitize.outputs.refname }}-${{ github.run_number }}.${{ github.run_attempt }}
    steps:
      - name: print-vars
        run: env
      # - name: print-github-context
        # run: echo '${{ toJSON(github) }}'
      - name: sanitize-ref-name
        id: sanitize
        run: 'echo "::set-output name=refname::$(echo $GITHUB_REF_NAME | sed -r ''s/([^a-zA-Z0-9.]+)/-/g'' | sed -r ''s/(^-|-$)//g'')"'
      - name: print-sanitizef-ref-name
        run: echo ${{ steps.sanitize.outputs.refname }}

  java:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v3
      - name: build-commons
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.common \
          --cache-to type=inline \
          --cache-from mazorn/metas-mvn-common:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mvn-common:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mvn-common:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: build-backend
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.backend \
          --cache-to type=inline \
          --cache-from mazorn/metas-mvn-backend:${{ needs.init.outputs.tag-floating }} \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mvn-backend:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mvn-backend:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: build-camel
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.camel \
          --cache-to type=inline \
          --cache-from mazorn/metas-mvn-camel:${{ needs.init.outputs.tag-floating }} \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mvn-camel:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mvn-camel:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: push-images
        run: |
          echo ${{ secrets.DOCKERHUB_RW_TOKEN }} | docker login --username mazorn --password-stdin
          docker push mazorn/metas-mvn-common:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-mvn-common:${{ needs.init.outputs.tag-floating }}
          docker push mazorn/metas-mvn-backend:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-mvn-backend:${{ needs.init.outputs.tag-floating }}
          docker push mazorn/metas-mvn-camel:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-mvn-camel:${{ needs.init.outputs.tag-floating }}
          docker logout

  frontend:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - uses: actions/checkout@v3
      - name: build-frontend
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.frontend \
          --cache-to type=inline \
          --cache-from mazorn/metas-frontend:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-frontend:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-frontend:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: build-mobile
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.mobile \
          --cache-to type=inline \
          --cache-from mazorn/metas-mobile:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mobile:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-mobile:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: push-images
        run: |
          echo ${{ secrets.DOCKERHUB_RW_TOKEN }} | docker login --username mazorn --password-stdin
          docker push mazorn/metas-frontend:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-frontend:${{ needs.init.outputs.tag-floating }}
          docker push mazorn/metas-mobile:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-mobile:${{ needs.init.outputs.tag-floating }}
          docker logout

  backend:
    runs-on: ubuntu-latest
    needs: [init, java]
    steps:
      - uses: actions/checkout@v3
      - name: build-api
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.backend.api \
          --cache-to type=inline \
          --cache-from mazorn/metas-api:${{ needs.init.outputs.tag-floating }} \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-api:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-api:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: build-app
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.backend.app \
          --cache-to type=inline \
          --cache-from mazorn/metas-app:${{ needs.init.outputs.tag-floating }} \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-app:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-app:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: build-externalsystems
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.camel.externalsystems \
          --cache-to type=inline \
          --cache-from mazorn/metas-externalsystems:${{ needs.init.outputs.tag-floating }} \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-externalsystems:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-externalsystems:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: build-db
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.db-standalone \
          --cache-to type=inline \
          --cache-from mazorn/metas-db:${{ needs.init.outputs.tag-floating }} \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-db:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-db:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: build-db-preloaded
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.db-preloaded \
          --cache-to type=inline \
          --cache-from mazorn/metas-db:${{ needs.init.outputs.tag-floating }}-preloaded \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-db:${{ needs.init.outputs.tag-floating }}-preloaded \
          -t mazorn/metas-db:${{ needs.init.outputs.tag-fixed }}-preloaded \
          .
      - name: push-images
        run: |
          echo ${{ secrets.DOCKERHUB_RW_TOKEN }} | docker login --username mazorn --password-stdin
          docker push mazorn/metas-api:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-api:${{ needs.init.outputs.tag-floating }}
          docker push mazorn/metas-app:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-app:${{ needs.init.outputs.tag-floating }}
          docker push mazorn/metas-externalsystems:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-externalsystems:${{ needs.init.outputs.tag-floating }}
          docker push mazorn/metas-db:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-db:${{ needs.init.outputs.tag-floating }}
          docker push mazorn/metas-db:${{ needs.init.outputs.tag-fixed }}-preloaded
          docker push mazorn/metas-db:${{ needs.init.outputs.tag-floating }}-preloaded
          docker logout

  junit:
    runs-on: ubuntu-latest
    needs: [init, java]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: run-junit-tests
        env:
          mysecret: ${{ secrets.TESTMO_TOKEN }}
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.junit \
          --cache-to type=inline \
          --cache-from mazorn/metas-junit:${{ needs.init.outputs.tag-floating }} \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          --secret id=mysecret \
          -t mazorn/metas-junit:${{ needs.init.outputs.tag-floating }} \
          .
      - name: push-result-image
        run: |
          echo ${{ secrets.DOCKERHUB_RW_TOKEN }} | docker login --username mazorn --password-stdin
          docker push mazorn/metas-junit:${{ needs.init.outputs.tag-floating }}
          docker logout
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: metasfresh
      - name: push-results
        env:
          runurl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          docker run --rm -v "$(pwd)/junit:/reports" mazorn/metas-junit:${{ needs.init.outputs.tag-floating }}
          find junit -type d -links 2 -exec testspace [{}]{}/*.xml \;

  cucumber:
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: build-cucumber
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.cucumber \
          --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-cucumber:${{ needs.init.outputs.tag-floating }} \
          -t mazorn/metas-cucumber:${{ needs.init.outputs.tag-fixed }} \
          .
      - name: push-images
        run: |
          echo ${{ secrets.DOCKERHUB_RW_TOKEN }} | docker login --username mazorn --password-stdin
          docker push mazorn/metas-cucumber:${{ needs.init.outputs.tag-fixed }}
          docker push mazorn/metas-cucumber:${{ needs.init.outputs.tag-floating }}
          docker logout
      - name: run-tests
        env:
          refname: ${{ needs.init.outputs.tag-fixed }}
        timeout-minutes: 60
        run: |
          mkdir cucumber
          docker cp "$(docker create --name tempcopytainer mazorn/metas-cucumber:$refname):/compose.yml" . && docker rm tempcopytainer
          docker-compose up --abort-on-container-exit --exit-code-from cucumber
          docker-compose down
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: metasfresh
      - name: push-results
        env:
          runurl: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          find cucumber -type d -links 2 -exec testspace [{}]{}/*.xml \;

  redeploy:
    runs-on: ubuntu-latest
    needs: [init, backend, frontend]
    environment: 'dev'
    if: github.ref == 'refs/heads/mzorn/wip-local-dockerbuilds'
    steps:
      - name: remove-running-pods
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG }}
        with:
          args: delete -n dev --all pods




# DISCARDED CYPRESS
# - name: build-e2e
# run: |
# docker buildx build \
# -f docker-builds/Dockerfile.e2e \
# --build-arg REFNAME=${{ needs.init.outputs.tag-floating }} \
# -t mazorn/metas-e2e:${{ needs.init.outputs.tag-floating }} \
# -t mazorn/metas-e2e:${{ needs.init.outputs.tag-fixed }} \
# .
# ---
# docker push mazorn/metas-e2e:${{ needs.init.outputs.tag-fixed }}
# docker push mazorn/metas-e2e:${{ needs.init.outputs.tag-floating }}
# ---
# cypress:
# if: ${{ false }}  # disable for now
# runs-on: ubuntu-latest
# needs: [init, integration-tests]
# environment: 'test'
# continue-on-error: true
# steps:
# - name: run-cypress-tests
# env:
# mysecret: ${{ secrets.TESTMO_TOKEN }}
# refname: ${{ needs.init.outputs.tag-fixed }}
# timeout-minutes: 240
# run: |
# echo "$mysecret" > mysecret
# docker cp "$(docker create --name tempcopytainer mazorn/metas-e2e:$refname):/compose.yml" . && docker rm tempcopytainer
# docker-compose up --abort-on-container-exit --exit-code-from cucumber
# docker-compose down